// <auto-generated />
using System;
using Identity_Login.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity_Login.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251003185932_Classification")]
    partial class Classification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity_Login.Models.dbModels.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassificationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassificationId");

                    b.ToTable("classifications");

                    b.HasData(
                        new
                        {
                            ClassificationId = 1,
                            Name = "Type I, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 2,
                            Name = "Type II, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 3,
                            Name = "Type II, Class 2 (BLACK)"
                        },
                        new
                        {
                            ClassificationId = 4,
                            Name = "Type II, Class 2 (BLUE-A)"
                        },
                        new
                        {
                            ClassificationId = 5,
                            Name = "Type II, Class 2 (BORDEAUX RED)"
                        },
                        new
                        {
                            ClassificationId = 6,
                            Name = "Type II, Class 2 (BROWN-GL)"
                        },
                        new
                        {
                            ClassificationId = 7,
                            Name = "Type II, Class 2 (CAMO BROWN)"
                        },
                        new
                        {
                            ClassificationId = 8,
                            Name = "Type II, Class 2 (DARK BLUE)"
                        },
                        new
                        {
                            ClassificationId = 9,
                            Name = "Type II, Class 2 (GOLD S)"
                        },
                        new
                        {
                            ClassificationId = 10,
                            Name = "Type II, Class 2 (GREEN AEN)"
                        },
                        new
                        {
                            ClassificationId = 11,
                            Name = "Type II, Class 2 (GREY)"
                        },
                        new
                        {
                            ClassificationId = 12,
                            Name = "Type II, Class 2 (LANTZ MEDICAL BLUE)"
                        },
                        new
                        {
                            ClassificationId = 13,
                            Name = "Type II, Class 2 (NEON PINK)"
                        },
                        new
                        {
                            ClassificationId = 14,
                            Name = "Type II, Class 2 (OLIVE DRAB)"
                        },
                        new
                        {
                            ClassificationId = 15,
                            Name = "Type II, Class 2 (ORANGE 2B)"
                        },
                        new
                        {
                            ClassificationId = 16,
                            Name = "Type II, Class 2 (TEAL)"
                        },
                        new
                        {
                            ClassificationId = 17,
                            Name = "Type II, Class 2 (VIOLET 3D)"
                        },
                        new
                        {
                            ClassificationId = 18,
                            Name = "Type II, Class 2 (YELLOW 4A)"
                        },
                        new
                        {
                            ClassificationId = 19,
                            Name = "Type III, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 20,
                            Name = "Type III, Class 1 (CLEAR) W/ PTFE TEFLON"
                        },
                        new
                        {
                            ClassificationId = 21,
                            Name = "Type III, Class 1 (CLEAR)(2 MIL)"
                        },
                        new
                        {
                            ClassificationId = 22,
                            Name = "Type III, Class 2 (BLACK)"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcessId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("JobProcesses");

                    b.HasData(
                        new
                        {
                            ProcessId = 1,
                            Description = "Handles anodizing jobs",
                            IsDeleted = false,
                            Name = "Anodizing Process"
                        },
                        new
                        {
                            ProcessId = 2,
                            Description = "Handles passivation jobs",
                            IsDeleted = false,
                            Name = "Passivation Process"
                        },
                        new
                        {
                            ProcessId = 3,
                            Description = "Handles black oxide jobs",
                            IsDeleted = false,
                            Name = "Black Oxide Process"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcessStage", b =>
                {
                    b.Property<int>("JobProcessStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobProcessStageId"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<int>("StageStatus")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("JobProcessStageId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobId");

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("JobProcessStages");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.Property<int>("ProcessStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessStepId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcessStepId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcessId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ProcessSteps");

                    b.HasData(
                        new
                        {
                            ProcessStepId = 1,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Create router/work order then parts are ready for racking",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 2,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 3,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Rack parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 4,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Masking (some parts may need this process)",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 5,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Anodize Process or Chemical conversion",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 6,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Pack up parts",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 7,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Ready for shipping",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 8,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Create router/work order then parts are ready for racking",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 9,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 10,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Rack parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 11,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Passivation process",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 12,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Dry parts",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 13,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Pack up parts",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 14,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Ready for shipping",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 15,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Shipped",
                            StepOrder = 8
                        },
                        new
                        {
                            ProcessStepId = 16,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Create router/work order then parts are ready for black oxide",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 17,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Ready for Black Oxide",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 18,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Black oxide parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 19,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Pack up parts",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 20,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Ready for Shipping",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 21,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Shipped",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 22,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Shipped",
                            StepOrder = 8
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int?>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrawingNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Materail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RCVDBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerbalNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("RouterJobs");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.StaffStationMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MappingId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("StaffStationMappings");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Identity_Login.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcessStage", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.RouterJob", "RouterJob")
                        .WithMany("ProcessStages")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.dbModels.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProcessStep");

                    b.Navigation("RouterJob");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.JobProcess", "JobProcess")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobProcess");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.HasOne("Identity_Login.Models.dbModels.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Classification");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.StaffStationMapping", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id");

                    b.HasOne("Identity_Login.Models.dbModels.Station", "Station")
                        .WithMany("StaffMembers")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("ApplicationUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Station");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.ProcessStep", "ProcessStep")
                        .WithMany("Stations")
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProcessStep");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.Navigation("ProcessStages");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
