// <auto-generated />
using System;
using Identity_Login.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity_Login.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313193117_blackOxideMinchangs")]
    partial class blackOxideMinchangs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity_Login.Models.dbModels.ASF", b =>
                {
                    b.Property<int>("ASFId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ASFId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ASFId");

                    b.ToTable("ASFs");

                    b.HasData(
                        new
                        {
                            ASFId = 1,
                            Name = "8 ASF"
                        },
                        new
                        {
                            ASFId = 2,
                            Name = "10 ASF"
                        },
                        new
                        {
                            ASFId = 3,
                            Name = "12 ASF"
                        },
                        new
                        {
                            ASFId = 4,
                            Name = "16 ASF"
                        },
                        new
                        {
                            ASFId = 5,
                            Name = "24 ASF"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassificationId"));

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassificationId");

                    b.ToTable("classifications");

                    b.HasData(
                        new
                        {
                            ClassificationId = 1,
                            Minutes = 12,
                            Name = "Type I, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 2,
                            Minutes = 18,
                            Name = "Type II, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 3,
                            Minutes = 45,
                            Name = "Type II, Class 2 (BLACK)"
                        },
                        new
                        {
                            ClassificationId = 4,
                            Minutes = 38,
                            Name = "Type II, Class 2 (BLUE-A)"
                        },
                        new
                        {
                            ClassificationId = 5,
                            Minutes = 38,
                            Name = "Type II, Class 2 (BORDEAUX RED)"
                        },
                        new
                        {
                            ClassificationId = 6,
                            Minutes = 30,
                            Name = "Type II, Class 2 (BROWN-GL)"
                        },
                        new
                        {
                            ClassificationId = 7,
                            Minutes = 30,
                            Name = "Type II, Class 2 (CAMO BROWN)"
                        },
                        new
                        {
                            ClassificationId = 8,
                            Minutes = 45,
                            Name = "Type II, Class 2 (DARK BLUE)"
                        },
                        new
                        {
                            ClassificationId = 9,
                            Minutes = 30,
                            Name = "Type II, Class 2 (GOLD S)"
                        },
                        new
                        {
                            ClassificationId = 10,
                            Minutes = 45,
                            Name = "Type II, Class 2 (GREEN AEN)"
                        },
                        new
                        {
                            ClassificationId = 11,
                            Minutes = 12,
                            Name = "Type II, Class 2 (GREY)"
                        },
                        new
                        {
                            ClassificationId = 12,
                            Minutes = 25,
                            Name = "Type II, Class 2 (LANTZ MEDICAL BLUE)"
                        },
                        new
                        {
                            ClassificationId = 13,
                            Minutes = 30,
                            Name = "Type II, Class 2 (NEON PINK)"
                        },
                        new
                        {
                            ClassificationId = 14,
                            Minutes = 35,
                            Name = "Type II, Class 2 (OLIVE DRAB)"
                        },
                        new
                        {
                            ClassificationId = 15,
                            Minutes = 38,
                            Name = "Type II, Class 2 (ORANGE 2B)"
                        },
                        new
                        {
                            ClassificationId = 16,
                            Minutes = 38,
                            Name = "Type II, Class 2 (TEAL)"
                        },
                        new
                        {
                            ClassificationId = 17,
                            Minutes = 45,
                            Name = "Type II, Class 2 (VIOLET 3D)"
                        },
                        new
                        {
                            ClassificationId = 18,
                            Minutes = 15,
                            Name = "Type II, Class 2 (YELLOW 4A)"
                        },
                        new
                        {
                            ClassificationId = 19,
                            Minutes = 105,
                            Name = "Type III, Class 1 (CLEAR)"
                        },
                        new
                        {
                            ClassificationId = 20,
                            Minutes = 105,
                            Name = "Type III, Class 1 (CLEAR) W/ PTFE TEFLON"
                        },
                        new
                        {
                            ClassificationId = 21,
                            Minutes = 140,
                            Name = "Type III, Class 1 (CLEAR)(2 MIL)"
                        },
                        new
                        {
                            ClassificationId = 22,
                            Minutes = 105,
                            Name = "Type III, Class 2 (BLACK)"
                        },
                        new
                        {
                            ClassificationId = 23,
                            Minutes = 30,
                            Name = "ASTM A 967, NITRIC"
                        },
                        new
                        {
                            ClassificationId = 24,
                            Minutes = 30,
                            Name = "ASTM A 967, CITRIC"
                        },
                        new
                        {
                            ClassificationId = 25,
                            Minutes = 15,
                            Name = "Black Oxide"
                        },
                        new
                        {
                            ClassificationId = 26,
                            Minutes = 0,
                            Name = "Stainless Steel"
                        },
                        new
                        {
                            ClassificationId = 27,
                            Minutes = 0,
                            Name = "Steel"
                        },
                        new
                        {
                            ClassificationId = 28,
                            Minutes = 15,
                            Name = "Type I Gold Class 1A Chem Film"
                        },
                        new
                        {
                            ClassificationId = 29,
                            Minutes = 10,
                            Name = "Type I Gold Class 3 Chem Film"
                        },
                        new
                        {
                            ClassificationId = 30,
                            Minutes = 15,
                            Name = "Type II Clear Class 1A Chem Film"
                        },
                        new
                        {
                            ClassificationId = 31,
                            Minutes = 10,
                            Name = "Type II Clear Class 3 Chem Film"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcessId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("JobProcesses");

                    b.HasData(
                        new
                        {
                            ProcessId = 1,
                            Description = "Handles anodizing jobs",
                            IsDeleted = false,
                            Name = "Anodizing Process"
                        },
                        new
                        {
                            ProcessId = 2,
                            Description = "Handles passivation jobs (method 1)",
                            IsDeleted = false,
                            Name = "Passivation Process (Method 1)"
                        },
                        new
                        {
                            ProcessId = 3,
                            Description = "Handles passivation jobs (method 2)",
                            IsDeleted = false,
                            Name = "Passivation Process (Method 2)"
                        },
                        new
                        {
                            ProcessId = 4,
                            Description = "Handles black oxide jobs",
                            IsDeleted = false,
                            Name = "Black Oxide Process"
                        },
                        new
                        {
                            ProcessId = 5,
                            Description = "Handles chemical conversion jobs",
                            IsDeleted = false,
                            Name = "Chemical Conversion"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcessStage", b =>
                {
                    b.Property<int>("JobProcessStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobProcessStageId"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<int>("StageStatus")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("JobProcessStageId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobId");

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("JobProcessStages");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Materail", b =>
                {
                    b.Property<int>("MaterailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterailId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterailId");

                    b.ToTable("Materails");

                    b.HasData(
                        new
                        {
                            MaterailId = 1,
                            Name = "5052 AL"
                        },
                        new
                        {
                            MaterailId = 2,
                            Name = "6061 AL"
                        },
                        new
                        {
                            MaterailId = 3,
                            Name = "7000 AL"
                        },
                        new
                        {
                            MaterailId = 4,
                            Name = "MIC-6 AL"
                        },
                        new
                        {
                            MaterailId = 5,
                            Name = "Stainless steel"
                        },
                        new
                        {
                            MaterailId = 6,
                            Name = "Steel"
                        },
                        new
                        {
                            MaterailId = 7,
                            Name = "Material 2024"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.Property<int>("ProcessStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessStepId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcessStepId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcessId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ProcessSteps");

                    b.HasData(
                        new
                        {
                            ProcessStepId = 1,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Create router/work order",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 2,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 3,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Rack parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 4,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Masking (some parts may need this process)",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 5,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Anodize Process or Chemical conversion",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 6,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Pack up parts",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 7,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Ready for shipping",
                            StepOrder = 8
                        },
                        new
                        {
                            ProcessStepId = 8,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "Shipped",
                            StepOrder = 9
                        },
                        new
                        {
                            ProcessStepId = 9,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Create router/work order",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 10,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 11,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Rack parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 12,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Passivation process",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 13,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Dry parts",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 14,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Pack up parts",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 15,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Ready for shipping",
                            StepOrder = 8
                        },
                        new
                        {
                            ProcessStepId = 16,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "Shipped",
                            StepOrder = 9
                        },
                        new
                        {
                            ProcessStepId = 17,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Create router/work order",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 18,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 19,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Rack parts",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 20,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Passivation process",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 21,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Dry parts",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 22,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Pack up parts",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 23,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Ready for shipping",
                            StepOrder = 8
                        },
                        new
                        {
                            ProcessStepId = 24,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "Shipped",
                            StepOrder = 9
                        },
                        new
                        {
                            ProcessStepId = 25,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Create router/work order",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 26,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Ready for racking",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 27,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Black oxide parts",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 28,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Pack up parts",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessStepId = 29,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Ready for Shipping",
                            StepOrder = 6
                        },
                        new
                        {
                            ProcessStepId = 30,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "Shipped",
                            StepOrder = 7
                        },
                        new
                        {
                            ProcessStepId = 38,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 5,
                            StepName = "Create router/work order",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessStepId = 31,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 5,
                            StepName = "Class 1A Thick Coating",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessStepId = 32,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 5,
                            StepName = "Class 3 Thin Coating",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessStepId = 37,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 5,
                            StepName = "In-Process",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 33,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 1,
                            StepName = "In-Process",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 34,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 2,
                            StepName = "In-Process",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 35,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 3,
                            StepName = "In-Process",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessStepId = 36,
                            IsDeleted = false,
                            IsOptional = false,
                            ProcessId = 4,
                            StepName = "In-Process",
                            StepOrder = 3
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int?>("ASFId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DisappearAfterShipped")
                        .HasColumnType("bit");

                    b.Property<string>("DrawingNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaterailId")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RCVDBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RunTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ShippedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("SurfaceArea")
                        .HasColumnType("float");

                    b.Property<double?>("TotalIn2OfRunRight")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerbalNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobId");

                    b.HasIndex("ASFId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MaterailId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("RunTypeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("RouterJobs");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RunType", b =>
                {
                    b.Property<int>("RunTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RunTypeId");

                    b.ToTable("RunTypes");

                    b.HasData(
                        new
                        {
                            RunTypeId = 1,
                            Name = "ETCH 3 MIN"
                        },
                        new
                        {
                            RunTypeId = 2,
                            Name = "ETCH 5 MIN"
                        },
                        new
                        {
                            RunTypeId = 3,
                            Name = "EXPED"
                        },
                        new
                        {
                            RunTypeId = 4,
                            Name = "NO ETCH"
                        },
                        new
                        {
                            RunTypeId = 5,
                            Name = "NO ETCH - CAST MTRL"
                        },
                        new
                        {
                            RunTypeId = 6,
                            Name = "NO ETCH/5 MIN DESMUT"
                        },
                        new
                        {
                            RunTypeId = 7,
                            Name = "NO SEAL"
                        },
                        new
                        {
                            RunTypeId = 8,
                            Name = "NO SEAL/PTFE TEFLON"
                        },
                        new
                        {
                            RunTypeId = 9,
                            Name = "PTFE TEFLON"
                        },
                        new
                        {
                            RunTypeId = 10,
                            Name = "RUN ON LG AL RACK"
                        },
                        new
                        {
                            RunTypeId = 11,
                            Name = "RUN ON MD AL RACK"
                        },
                        new
                        {
                            RunTypeId = 12,
                            Name = "RUN ON ROUND RACK"
                        },
                        new
                        {
                            RunTypeId = 13,
                            Name = "RUN ON SQ RACK"
                        },
                        new
                        {
                            RunTypeId = 14,
                            Name = "STRIP 10 MIN/ETCH 5 MIN"
                        },
                        new
                        {
                            RunTypeId = 15,
                            Name = "STRP 6 MIN/ETCH 2 MIN"
                        },
                        new
                        {
                            RunTypeId = 16,
                            Name = "STRIP ONLY"
                        },
                        new
                        {
                            RunTypeId = 17,
                            Name = "STRIP/ RE-ANODIZE"
                        },
                        new
                        {
                            RunTypeId = 18,
                            Name = "2 Min Etch"
                        },
                        new
                        {
                            RunTypeId = 19,
                            Name = "Dichromate Seal"
                        },
                        new
                        {
                            RunTypeId = 20,
                            Name = "Hot Water Seal"
                        });
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.StaffStationMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MappingId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("StaffStationMappings");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.UploadImage", b =>
                {
                    b.Property<int>("UploadImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UploadImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouterJobId")
                        .HasColumnType("int");

                    b.HasKey("UploadImageId");

                    b.HasIndex("RouterJobId");

                    b.ToTable("UploadImage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Identity_Login.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcessStage", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.RouterJob", "RouterJob")
                        .WithMany("ProcessStages")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.dbModels.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProcessStep");

                    b.Navigation("RouterJob");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.JobProcess", "JobProcess")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobProcess");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.HasOne("Identity_Login.Models.dbModels.ASF", "ASF")
                        .WithMany()
                        .HasForeignKey("ASFId");

                    b.HasOne("Identity_Login.Models.dbModels.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.Materail", "Materail")
                        .WithMany()
                        .HasForeignKey("MaterailId");

                    b.HasOne("Identity_Login.Models.dbModels.JobProcess", "JobProcess")
                        .WithMany()
                        .HasForeignKey("ProcessId");

                    b.HasOne("Identity_Login.Models.dbModels.RunType", "RunType")
                        .WithMany()
                        .HasForeignKey("RunTypeId");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("ASF");

                    b.Navigation("Classification");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobProcess");

                    b.Navigation("Materail");

                    b.Navigation("RunType");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.StaffStationMapping", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id");

                    b.HasOne("Identity_Login.Models.dbModels.Station", "Station")
                        .WithMany("StaffMembers")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("ApplicationUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Station");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.HasOne("Identity_Login.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Identity_Login.Models.dbModels.ProcessStep", "ProcessStep")
                        .WithMany("Stations")
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity_Login.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProcessStep");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.UploadImage", b =>
                {
                    b.HasOne("Identity_Login.Models.dbModels.RouterJob", "RouterJob")
                        .WithMany("UploadImages")
                        .HasForeignKey("RouterJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouterJob");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.JobProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.ProcessStep", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.RouterJob", b =>
                {
                    b.Navigation("ProcessStages");

                    b.Navigation("UploadImages");
                });

            modelBuilder.Entity("Identity_Login.Models.dbModels.Station", b =>
                {
                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
